/**
 * "Are these two the same person?" — the deterministic half.
 *
 * ══ THE ONE RULE THIS MODULE EXISTS TO HOLD ═════════════════════════════════
 *
 * **A name is never an identity.** `src/lib/inbox/threading.ts` settled it for
 * conversations and the reason has not changed: half the guesthouses in this
 * country have had two guests called דוד כהן. Here it is expressed as a
 * weight — a name is worth 0.12 out of a threshold of 0.85, so two identical
 * names with nothing else in common cannot reach it, and neither can two
 * identical names plus an identical document number (0.20). Only a shared
 * telephone number, or a shared email plus something, gets there.
 *
 * ══ THIS MODULE DOES NOT NORMALISE TELEPHONE NUMBERS, DELIBERATELY ══════════
 *
 * `threading.ts` exports `normalisePhone`, and it is NOT reused here — which
 * is the one place this file departs from it, so the reason is written out.
 *
 * The deduplication key in this product is `guests.phone_e164`, a stored
 * column generated by `public.normalize_phone_il`. `leads.phone_e164` is
 * generated by the same function. Comparing them is therefore an equality test
 * between two values the database computed, and a second normaliser in
 * TypeScript would be a second answer to "is this the same number" — one that
 * decides who gets merged. `threading.ts` normalises because a conversation's
 * contact columns are free text with no generated column behind them; a lead
 * and a guest both have one, and using it is strictly better than agreeing
 * with a copy of it.
 *
 * `normaliseEmail` IS reused, unchanged: `guests.email` is `citext` and
 * `leads.email_normalized` is `lower(btrim(…))`, which is exactly what that
 * function does — case and surrounding space, and deliberately not Gmail's
 * dot-and-plus rules, which belong to one provider and not to the internet.
 *
 * ══ EMAIL IS A CANDIDATE KEY, NOT AN IDENTITY (ח40-06) ══════════════════════
 *
 * A couple booking two stays from one address is the ordinary case, not a
 * duplicate. So an email match SUGGESTS and never attaches; only a telephone
 * match attaches, and that is a database-level equality (ח40-08).
 */

import { normaliseEmail } from '../inbox/threading'
// §7.1 says the score is rounded with `roundTo(x, 2)`, and this is that
// function. Taken from the metrics module rather than written again: a second
// rounding is a second answer at the boundary, and the boundary here is 0.85.
import { roundTo } from '../metrics/rounding'

/* ------------------------------------------------- attaching a new lead -- */

/**
 * A guest, reduced to what a match may look at.
 *
 * Note what is absent: a date of birth and an address. They are in `guests`,
 * they identify a person very well, and they are not here — the merge screen
 * this feeds must not become a reason to read them.
 */
export interface MatchableGuest {
  id: string
  fullName: string
  /** `guests.phone_e164`, as the database generated it. Never re-derived. */
  phoneE164: string | null
  email: string | null
  idDocumentNumber?: string | null
  idDocumentCountry?: string | null
}

export interface MatchableLead {
  /** `leads.phone_e164`, as the database generated it. */
  phoneE164: string | null
  emailNormalized: string | null
}

export type Attachment =
  /** Exactly one guest shares the normalised telephone number. Attach it. */
  | { kind: 'attach'; guestId: string }
  /**
   * Somebody shares the email address and nobody shares the number. A person
   * decides; the lead is written with no `guest_id` until they do.
   */
  | { kind: 'suggest'; guestIds: readonly string[] }
  /** Nothing to go on. A new enquiry from somebody not on file. */
  | { kind: 'none' }

/**
 * ח40-08 · Creating a lead NEVER creates a guest and never guesses.
 *
 * It attaches on an exact `phone_e164` match, suggests on an email match, and
 * otherwise leaves `guest_id` null. The third outcome is a real answer: a
 * second guest card for somebody already on file is the failure §17 of the
 * specification opens with, and a lead with no guest attached costs nothing
 * that a wrong attachment does not cost more.
 *
 * `candidates` must already be scoped to one organization — deduplication is
 * per tenant (ח40-05), and a global one would leak one business's customer
 * list to another through a collision.
 */
export function attachmentFor(
  lead: MatchableLead,
  candidates: readonly MatchableGuest[],
): Attachment {
  if (lead.phoneE164 !== null) {
    const byPhone = candidates.filter(
      (guest) => guest.phoneE164 !== null && guest.phoneE164 === lead.phoneE164,
    )
    // `guests_organization_phone_idx` makes more than one impossible among
    // live rows. If two ever come back, something has been merged badly and
    // guessing between them is the last thing to do.
    if (byPhone.length === 1) return { kind: 'attach', guestId: byPhone[0].id }
    if (byPhone.length > 1) {
      return { kind: 'suggest', guestIds: byPhone.map((guest) => guest.id) }
    }
  }

  if (lead.emailNormalized !== null) {
    const byEmail = candidates.filter(
      (guest) => normaliseEmail(guest.email) === lead.emailNormalized,
    )
    if (byEmail.length > 0) {
      return { kind: 'suggest', guestIds: byEmail.map((guest) => guest.id) }
    }
  }

  return { kind: 'none' }
}

/* ----------------------------------------------------- the match score -- */

/** §7.1, weights included so the arithmetic can be read beside them. */
export const MATCH_WEIGHTS = {
  phone: 0.6,
  email: 0.2,
  name: 0.12,
  document: 0.08,
} as const

/** ≥ this, and the product offers a merge. Below it, it says nothing. */
export const MERGE_SUGGESTION_THRESHOLD = 0.85
/** Between this and the threshold: "this might be the same person". */
export const POSSIBLE_MATCH_THRESHOLD = 0.6

export interface MatchScore {
  score: number
  phone: number
  email: number
  name: number
  document: number
  /**
   * False when neither row carried a document number, so the reader knows the
   * score was reached without that component rather than that it disagreed.
   * The threshold is still reachable: 0.60 + 0.20 + 0.12 = 0.92.
   */
  documentsCompared: boolean
}

/**
 * How alike are these two guest rows?
 *
 * Deterministic and testable on purpose. §12.3 of the specification is
 * explicit that the model does not run this: a decision that mixes up two
 * people's money has to be reproducible, and a language model is not. The AI's
 * job is to phrase the explanation, never to reach the conclusion.
 */
export function scoreMatch(a: MatchableGuest, b: MatchableGuest): MatchScore {
  const phone = phoneComponent(a.phoneE164, b.phoneE164)
  const email = emailComponent(a.email, b.email)
  const name = jaroWinkler(normaliseName(a.fullName), normaliseName(b.fullName))

  const documentsCompared =
    isPresent(a.idDocumentNumber) && isPresent(b.idDocumentNumber)
  const document =
    documentsCompared &&
    a.idDocumentNumber!.trim() === b.idDocumentNumber!.trim() &&
    // The country as well. Two national id numbers from two countries that
    // happen to collide are two people, and passport numbers collide.
    (a.idDocumentCountry ?? null) === (b.idDocumentCountry ?? null)
      ? 1
      : 0

  const score =
    MATCH_WEIGHTS.phone * phone +
    MATCH_WEIGHTS.email * email +
    MATCH_WEIGHTS.name * name +
    MATCH_WEIGHTS.document * document

  return {
    score: roundTo(score, 2),
    phone,
    email,
    name: roundTo(name, 2),
    document,
    documentsCompared,
  }
}

export function suggestsMerge(score: MatchScore): boolean {
  return score.score >= MERGE_SUGGESTION_THRESHOLD
}

export function worthMentioning(score: MatchScore): boolean {
  return (
    score.score >= POSSIBLE_MATCH_THRESHOLD &&
    score.score < MERGE_SUGGESTION_THRESHOLD
  )
}

/**
 * 1 for the same normalised number; 0.5 when the last seven digits agree and
 * the prefix does not.
 *
 * The half point is for the case that actually happens: the same person
 * entered once with a country code and once without, in a way
 * `normalize_phone_il` could not reconcile — ח40-03 documents that a number
 * beginning `972` with no `+` is read as Israeli, so a real collision exists
 * and pretending otherwise would hide it. It is half a point and not a match,
 * which is the difference between "look at this" and "these are one person".
 */
function phoneComponent(a: string | null, b: string | null): number {
  if (a === null || b === null) return 0
  if (a === b) return 1
  const tailA = digitsOf(a).slice(-7)
  const tailB = digitsOf(b).slice(-7)
  if (tailA.length === 7 && tailA === tailB) return 0.5
  return 0
}

/**
 * 1 for the same address; 0.4 when the local part matches and the domain does
 * not.
 *
 * `dana@gmail.com` and `dana@company.co.il` are frequently one person and
 * frequently two, which is exactly what a partial score is for.
 */
function emailComponent(a: string | null, b: string | null): number {
  const left = normaliseEmail(a)
  const right = normaliseEmail(b)
  if (left === null || right === null) return 0
  if (left === right) return 1

  const localA = left.split('@')[0]
  const localB = right.split('@')[0]
  if (localA.length > 0 && localA === localB) return 0.4
  return 0
}

function digitsOf(value: string): string {
  return value.replace(/\D/g, '')
}

function isPresent(value: string | null | undefined): boolean {
  return typeof value === 'string' && value.trim().length > 0
}

/**
 * A Hebrew name, reduced to something two spellings of it can share.
 *
 * Collapses whitespace, strips the combining marks (niqqud and cantillation,
 * U+0591–U+05C7), and folds the Hebrew punctuation geresh ׳ and gershayim ״
 * onto the ASCII quotes people type instead of them. Lower-cased for Latin
 * script, which Hebrew ignores.
 *
 * It does NOT try to reconcile `ו׳` with `ואו` or any other spelling variant.
 * That was in the specification and it is left out on purpose: a
 * transliteration table is a long list of guesses, and every guess in here
 * moves a score toward merging two people.
 */
export function normaliseName(value: string): string {
  return value
    .normalize('NFC')
    .replace(/[֑-ׇ]/g, '')
    .replace(/׳/g, "'")
    .replace(/״/g, '"')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()
}

/**
 * Jaro-Winkler similarity, 0 to 1.
 *
 * The standard formulation: Jaro, then a bonus of up to four leading matching
 * characters at 0.1 each. It is here rather than from a dependency because it
 * is thirty lines and because a scoring function that decides whether two
 * customers are one person should be readable in the file that uses it.
 */
export function jaroWinkler(a: string, b: string): number {
  const jaro = jaroSimilarity(a, b)
  if (jaro === 0) return 0

  let prefix = 0
  const limit = Math.min(4, a.length, b.length)
  while (prefix < limit && a[prefix] === b[prefix]) prefix += 1

  return jaro + prefix * 0.1 * (1 - jaro)
}

function jaroSimilarity(a: string, b: string): number {
  if (a.length === 0 && b.length === 0) return 1
  if (a.length === 0 || b.length === 0) return 0
  if (a === b) return 1

  const window = Math.max(0, Math.floor(Math.max(a.length, b.length) / 2) - 1)
  const matchedA = new Array<boolean>(a.length).fill(false)
  const matchedB = new Array<boolean>(b.length).fill(false)

  let matches = 0
  for (let i = 0; i < a.length; i += 1) {
    const from = Math.max(0, i - window)
    const to = Math.min(i + window + 1, b.length)
    for (let j = from; j < to; j += 1) {
      if (matchedB[j] || a[i] !== b[j]) continue
      matchedA[i] = true
      matchedB[j] = true
      matches += 1
      break
    }
  }

  if (matches === 0) return 0

  let transpositions = 0
  let k = 0
  for (let i = 0; i < a.length; i += 1) {
    if (!matchedA[i]) continue
    while (!matchedB[k]) k += 1
    if (a[i] !== b[k]) transpositions += 1
    k += 1
  }

  const half = transpositions / 2
  return (
    (matches / a.length + matches / b.length + (matches - half) / matches) / 3
  )
}
