/**
 * The vocabulary of an enquiry.
 *
 * Every list here has a matching enum in `0074_leads_and_guest_merges.sql`.
 * The database is the authority — a value that is not in the enum cannot be
 * stored whatever this file says — and these exist so a screen can draw the
 * options and a test can enumerate them.
 */

export const LEAD_STATUSES = [
  'new',
  'contacted',
  'interested',
  'quote_sent',
  'negotiation',
  'booked',
  'lost',
] as const

export type LeadStatus = (typeof LEAD_STATUSES)[number]

export const LEAD_SOURCES = [
  'website',
  'phone',
  'whatsapp',
  'agent',
  'ota_enquiry',
  'social',
  'walk_in',
  'referral',
] as const

export type LeadSource = (typeof LEAD_SOURCES)[number]

export const LEAD_LOST_REASONS = [
  'price',
  'dates_unavailable',
  'no_response',
  'booked_elsewhere',
  'not_serious',
  'duplicate',
  'other',
] as const

export type LeadLostReason = (typeof LEAD_LOST_REASONS)[number]

/**
 * The statuses that are still being worked.
 *
 * Written as a filter over `LEAD_STATUSES` rather than as a literal list, so a
 * status added to the workflow lands on one side of the cut deliberately
 * rather than by being forgotten. `booked` and `lost` are the two that leave:
 * one became a stay and is counted there, the other did not and is counted in
 * the reasons breakdown.
 */
export const OPEN_LEAD_STATUSES: readonly LeadStatus[] = LEAD_STATUSES.filter(
  (status) => status !== 'booked' && status !== 'lost',
)

/**
 * One enquiry, as the domain reads it.
 *
 * `rawName`, `rawPhone` and `rawEmail` are what the person actually typed, and
 * they are kept beside the normalised forms rather than replaced by them: when
 * a deduplication later turns out to have joined two people, the only way to
 * see how is to still have the original.
 */
export interface Lead {
  id: string
  organizationId: string
  propertyId: string | null
  guestId: string | null
  status: LeadStatus
  source: LeadSource
  sourceDetail: string | null

  rawName: string | null
  rawPhone: string | null
  rawEmail: string | null
  /** Generated by `normalize_phone_il` in the database. Never computed here. */
  phoneE164: string | null
  /** Generated in the database. Case and surrounding space only. */
  emailNormalized: string | null

  requestedCheckIn: string | null
  requestedCheckOut: string | null
  partyAdults: number
  partyChildren: number
  partyInfants: number

  budgetAgorot: number | null
  message: string | null

  assignedToUserId: string | null
  assignedTeamId: string | null

  firstResponseAt: string | null
  nextActionAt: string | null
  statusChangedAt: string

  lostReason: LeadLostReason | null
  lostNote: string | null
  bookingId: string | null

  agentUserId: string | null
  agencyId: string | null

  createdAt: string
  createdByUserId: string | null
  version: number
}

/** Hebrew, for the board columns and the audit sentences. */
export const LEAD_STATUS_LABEL: Record<LeadStatus, string> = {
  new: 'חדש',
  contacted: 'יצרנו קשר',
  interested: 'מתעניין',
  quote_sent: 'נשלחה הצעה',
  negotiation: 'משא ומתן',
  booked: 'הפך להזמנה',
  lost: 'נסגר',
}

export const LEAD_SOURCE_LABEL: Record<LeadSource, string> = {
  website: 'האתר',
  phone: 'טלפון',
  whatsapp: 'וואטסאפ',
  agent: 'סוכן',
  ota_enquiry: 'פנייה מפלטפורמה',
  social: 'רשתות חברתיות',
  walk_in: 'הגיע לדלפק',
  referral: 'המלצה',
}

export const LEAD_LOST_REASON_LABEL: Record<LeadLostReason, string> = {
  price: 'המחיר',
  dates_unavailable: 'התאריכים לא היו זמינים',
  no_response: 'לא חזר אלינו',
  booked_elsewhere: 'הזמין במקום אחר',
  not_serious: 'לא פנייה רצינית',
  duplicate: 'כפילות',
  other: 'אחר',
}
