'use server'

/**
 * EXECUTION CONTEXT — SERVER ACTIONS. What the campaign screen can write.
 *
 * ══ TWO ACTIONS, AND THE ABSENCES ARE THE ARGUMENT ══════════════════════════
 *
 * `create` and `pause`. There is no delete and no edit of the discount terms,
 * and neither is an oversight:
 *
 *   · `0073_promotions_and_coupons.sql` refuses `delete` and `truncate` to
 *     every role. A campaign explains a price a guest paid; deleting it makes
 *     "why did this booking come to ₪6,232.76" unanswerable, and that question
 *     is asked by an accountant a year later, not by a manager this week. An
 *     action added here to delete would fail at the database, which is why the
 *     rule lives there and not only in this file.
 *
 *   · Editing `discount_value` would change what a campaign meant last week. A
 *     promotion is a commercial promise, and a new promise is a new promotion —
 *     the same sentence §12 uses to say what the pricing AI may never do.
 *
 * **Redeeming is not here either.** It happens while a booking is being taken,
 * from the booking path, and it goes through `public.redeem_discount` — never
 * through a count-then-insert in TypeScript. Putting a redeem button on a
 * campaign screen would invite exactly the code that loses the race.
 */

import { revalidatePath } from 'next/cache'

import { toSafeResponse, type SafeErrorBody } from '@/lib/errors'
import {
  SupabaseAuditWriter,
  SupabaseIdempotencyStore,
} from '@/lib/persistence'
import { definePromotionOperations } from '@/lib/promotions/operations'
import { PromotionRepository } from '@/lib/promotions/repository'
import type {
  PromotionAppliesTo,
  PromotionDiscountKind,
  PromotionKind,
} from '@/lib/promotions'
import { createClient } from '@/lib/supabase/server'

import { shellContext } from '../../../_lib/context'
import { domainEventBus } from '../../../_lib/events'
import { auditActorFor, transactionRunner } from '../../../_lib/wiring'

export type ActionResult<TData> =
  { ok: true; data: TData } | { ok: false; error: SafeErrorBody }

const SCREEN = '/promotions/campaigns'

async function ready(correlationId: string) {
  const context = await shellContext()

  if (!context || context.status !== 'ready') {
    return {
      ok: false as const,
      error: {
        code: context ? 'membership_not_active' : 'unauthenticated',
        message: context
          ? 'אין לך מרחב עבודה פעיל, ולכן לא ניתן לנהל מבצעים.'
          : 'החיבור למערכת פג. התחבר מחדש כדי להמשיך.',
        dataMessage: 'שום דבר לא נשמר.',
        retryMessage: context
          ? 'ניסיון חוזר לא יעזור עד שהחברות בארגון תופעל.'
          : 'ניסיון חוזר לא יעזור עד שתתחבר מחדש.',
        dataOutcome: 'not_saved' as const,
        retryable: false,
        correlationId,
      },
    }
  }

  return { ok: true as const, context }
}

async function services() {
  const db = await createClient()
  const { transactions } = transactionRunner(db)
  const repository = new PromotionRepository(db)

  return {
    operations: definePromotionOperations({
      db,
      loadPromotion: (organizationId, id) =>
        repository.promotion(organizationId, id),
    }),
    services: {
      audit: new SupabaseAuditWriter(db),
      events: domainEventBus(db),
      idempotency: new SupabaseIdempotencyStore(db),
      transactions,
    },
  }
}

/**
 * Declare a campaign.
 *
 * `idempotencyKey` is generated by the form when it is DISPLAYED, not when it
 * is submitted — §10's rule, and the reason is that a key regenerated on every
 * attempt is not a key. A double-clicked submit then replays rather than
 * creating a second campaign with a suffixed code.
 */
export async function createPromotionAction(input: {
  code: string
  name: string
  kind: PromotionKind
  discountKind: PromotionDiscountKind
  discountValue: number
  appliesTo: PromotionAppliesTo
  stackable: boolean
  exclusiveGroup?: string
  priority: number
  maxRedemptions?: number
  maxPerGuest?: number
  budgetAgorot?: number
  effectiveFrom: string
  effectiveTo?: string
  idempotencyKey: string
}): Promise<ActionResult<{ id: string }>> {
  const correlationId = crypto.randomUUID()
  const gate = await ready(correlationId)
  if (!gate.ok) return gate
  const { context } = gate

  try {
    const wired = await services()
    const { idempotencyKey, effectiveFrom, effectiveTo, ...rest } = input

    const outcome = await wired.operations.create.run({
      request: {
        // The schema parses the two instants; the action does not, so an
        // unparseable date is reported as a field issue on the field that
        // carried it rather than as a thrown RangeError with no field name.
        input: {
          ...rest,
          effectiveFrom,
          ...(effectiveTo === undefined ? {} : { effectiveTo }),
        },
        idempotencyKey,
      },
      context: {
        actor: context.actor,
        auditActor: auditActorFor(context.user),
        correlationId,
      },
      services: wired.services,
    })

    revalidatePath(SCREEN)
    return { ok: true, data: outcome.data }
  } catch (cause) {
    return { ok: false, error: toSafeResponse(cause, correlationId).error }
  }
}

/**
 * Stop offering a campaign, with a reason that is stored.
 *
 * Not a delete. The row survives, `deactivated_at` and `deactivated_by` are
 * stamped, and the reason is written to both the row and the audit event —
 * the row so the screen can show it, the audit event because that one cannot
 * be edited afterwards.
 *
 * A campaign that reached `max_redemptions` is already paused by the database
 * with the reason `max_redemptions_reached`, and the operation refuses to pause
 * it again rather than overwriting that sentence with a person's.
 */
export async function pausePromotionAction(input: {
  promotionId: string
  reason: string
}): Promise<ActionResult<{ id: string }>> {
  const correlationId = crypto.randomUUID()
  const gate = await ready(correlationId)
  if (!gate.ok) return gate
  const { context } = gate

  try {
    const wired = await services()

    const outcome = await wired.operations.pause.run({
      request: {
        input,
        // Derived, not supplied by the client: pausing one campaign is a
        // single act, and a second click is the same act. §10's rule for a
        // key the server can compute.
        idempotencyKey: `pause:${input.promotionId}`,
      },
      context: {
        actor: context.actor,
        auditActor: auditActorFor(context.user),
        correlationId,
        // §13: a sensitive action is not performed on the strength of a
        // permission alone. The reason travels on the context as well as in
        // the input, so the audit row carries it even if the operation's own
        // summary is ever reworded.
        reason: input.reason,
      },
      services: wired.services,
    })

    revalidatePath(SCREEN)
    return { ok: true, data: outcome.data }
  } catch (cause) {
    return { ok: false, error: toSafeResponse(cause, correlationId).error }
  }
}
