/**
 * A failure from `src/lib/errors`, shown the way the product shows failures.
 *
 * The whole point is that no wording is invented here. `toSafeResponse` is the
 * only sanctioned way an error leaves the server: it strips the technical
 * message, keeps the Hebrew `userMessage`, and carries the two sentences a user
 * actually needs — was my data saved, and is it safe to try again.
 * `fromSafeError` then takes that verbatim and adds only the headline, which is
 * the one thing a server has no opinion about. `ErrorState` renders it.
 *
 * WHERE THIS BELONGS. `src/components/states/`, beside `ErrorState` and
 * `error-copy.ts`. It is here because this work owns `src/components/calendar`
 * and not that directory, and a screen that swallowed a domain error rather
 * than reach across a boundary would be the worse trade. Moving it is a
 * two-line change and no call site would notice.
 */

import { ErrorState } from '@/components/states/error-state'
import { fromSafeError } from '@/components/states/error-copy'
import { toSafeResponse } from '@/lib/errors'

export type DomainErrorPanelProps = {
  error: unknown
  /**
   * Matches the server log entry for the same failure. Generated by the page
   * that caught the error, so the same id is in both places.
   */
  correlationId: string
  as?: 'h1' | 'h2' | 'h3'
}

export function DomainErrorPanel({
  error,
  correlationId,
  as = 'h2',
}: DomainErrorPanelProps) {
  const safe = toSafeResponse(error, correlationId)
  return <ErrorState presentation={fromSafeError(safe.error)} as={as} />
}
