/**
 * EXECUTION CONTEXT — PURE. What somebody typed, and what it could be.
 *
 * ══ WHY CLASSIFICATION IS ITS OWN MODULE ════════════════════════════════════
 *
 * Spec 6.0 §96 asks for one search across guest, phone, email, booking,
 * property, payment, owner, agent and task. The naive shape is one `ilike`
 * against nine tables, and it is wrong twice over.
 *
 * **It finds the wrong things.** `050-1234567` typed into a name column matches
 * nothing, and the guest whose number that is — the person actually being
 * looked for — is not returned. `/guests` has exactly this defect today: it
 * puts the raw string into an `ilike` pattern, so a number typed with dashes
 * never finds a guest stored as `+972…`. The database already solved this:
 * `guests.phone_e164` is generated by `normalize_phone_il` and carries a unique
 * index. A search that does not go through the same function is asking a
 * different question from the one the schema answers.
 *
 * **It costs nine queries to answer one.** A booking reference is `B` followed
 * by hex; an email has an `@`; a phone is digits and punctuation. Each of those
 * shapes rules most tables out before a single round trip.
 *
 * So this decides what the string IS, and the caller queries only what could
 * match. Pure, so the decision is testable without a database — and the rules
 * are the kind that get argued about, which is exactly the kind worth pinning.
 *
 * ══ A SHAPE IS A HINT, NEVER AN EXCLUSION ═══════════════════════════════════
 *
 * `4512` is a plausible booking reference and a plausible phone fragment and a
 * plausible nothing. When the shape is ambiguous every candidate kind stays in,
 * because a search that confidently returns the wrong three rows is worse than
 * one that returns eleven. Narrowing happens only where the shape is decisive:
 * an `@` is not a phone number, and a string with letters and no `@` is not a
 * phone number either.
 */

/** What the string looks like, structurally. */
export type QueryShape =
  /** Digits and phone punctuation. May still be a reference fragment. */
  | 'phone'
  /** Contains `@`. Nothing else looks like this. */
  | 'email'
  /** `B` and hex, the shape `0009` generates references in. */
  | 'reference'
  /** Anything else: a name, a street, a note. */
  | 'text'

/** The things §96 says one search must reach. */
export const SEARCH_KINDS = [
  'guest',
  'booking',
  'property',
  'unit',
  'task',
  'owner',
  'agent',
] as const

export type SearchKind = (typeof SEARCH_KINDS)[number]

export interface ParsedQuery {
  /** Trimmed and collapsed. Never the raw input. */
  readonly text: string
  readonly shape: QueryShape
  /**
   * Digits only, for the phone path. Present whenever the string contains at
   * least the digits a phone could be built from — including for a `text`
   * shape, because "דנה 0501234567" is a thing people type.
   */
  readonly digits: string | null
  /** Kinds worth querying for this string. Ordered by how likely they are. */
  readonly kinds: readonly SearchKind[]
}

/** Below this a search matches everything and means nothing. */
export const MIN_QUERY_LENGTH = 2

/**
 * A reference as `0009` writes it: `'B' || hex`.
 *
 * Anchored, because `B3F9` inside a sentence is not somebody quoting a booking
 * number — and the whole point of the shape is to rule other tables out, which
 * a loose match would not earn.
 */
const REFERENCE = /^b[0-9a-f]{4,16}$/i

/** Digits, spaces, dashes, parentheses and a leading plus. Nothing else. */
const PHONE_SHAPED = /^[+()\-.\s0-9]{6,}$/

export function parseQuery(raw: string): ParsedQuery | null {
  const text = raw.trim().replace(/\s+/g, ' ')
  if (text.length < MIN_QUERY_LENGTH) return null

  const digits = extractDigits(text)

  if (text.includes('@')) {
    // An email is only ever a person. Nothing else in the product carries one
    // as an identifier a human would search by.
    return { text, shape: 'email', digits: null, kinds: ['guest'] }
  }

  if (REFERENCE.test(text)) {
    // Decisive enough to lead with, and not decisive enough to be alone: a
    // property genuinely called "B12" exists somewhere, and refusing to look
    // would be the confident-and-wrong failure this module avoids.
    return {
      text,
      shape: 'reference',
      digits,
      kinds: ['booking', 'property', 'unit'],
    }
  }

  if (PHONE_SHAPED.test(text) && digits !== null) {
    // A guest first, because that is who a phone number identifies. An agent
    // and an owner are people too and are reached the same way.
    return {
      text,
      shape: 'phone',
      digits,
      kinds: ['guest', 'agent', 'owner', 'booking'],
    }
  }

  return { text, shape: 'text', digits, kinds: [...SEARCH_KINDS] }
}

/**
 * The digits in a string, or null when there are too few to be a number.
 *
 * Six is the floor because an Israeli number has nine or ten and a fragment
 * shorter than six matches most of a customer list — which is not a search
 * result, it is a list with extra steps.
 */
function extractDigits(text: string): string | null {
  const digits = text.replace(/\D/g, '')
  return digits.length >= 6 ? digits : null
}

/**
 * The `ilike` pattern for a free-text match, with the wildcards escaped.
 *
 * `%` and `_` are wildcards in `LIKE`, so a person searching for `50%` would
 * otherwise match every guest whose name contains `50`. Escaped with a
 * backslash, which is PostgREST's default escape character.
 */
export function likePattern(text: string): string {
  const escaped = text.replace(/[\\%_]/g, (char) => `\\${char}`)
  return `%${escaped}%`
}
