/**
 * Turning a consolidated run into an order, once.
 *
 * ── The idempotency key, and why it is derived rather than generated ──────
 *
 * A retry must not create a second order for the same requirement. That
 * sentence has a weak reading and a strong one, and the difference is a second
 * van.
 *
 * The WEAK reading is "the same HTTP request must not be processed twice". The
 * service pipeline already gives that: `OperationRequest.idempotencyKey` is
 * reserved before the work and replayed after it, scoped to the organization
 * and the operation. If the caller generates a fresh uuid per click, a
 * double-clicked button is safe.
 *
 * It protects nothing else. Two browser tabs, a mobile app and a laptop, a
 * scheduled job re-run after a deploy, a person on the phone to the office
 * while somebody at the property presses the same button — every one of those
 * is a different request with a different uuid, and the store has no opinion
 * about any of them. Each produces an order. Each order is sent. The provider
 * receives two messages, sends two vans, and invoices for both.
 *
 * So the key is DERIVED FROM THE WORK rather than generated by the caller:
 *
 *     provider · route · the day it is needed · the content of the lines
 *
 * Two callers who computed the same wash produce the same key and the second
 * one replays the first one's answer. A caller who computed a genuinely
 * different wash — an extra property joined the run, a quantity changed —
 * produces a different key and is allowed through, which is right: that IS a
 * different order.
 *
 * ── Why the day, and not the instant ──────────────────────────────────────
 *
 * Two people building the run four minutes apart would otherwise disagree in
 * the sixth decimal of a timestamp and produce two keys for one wash. The day
 * is the granularity at which a run is a run — `consolidation.ts` groups by it
 * for the same reason — so it is the granularity the key uses.
 *
 * ── Why the line content, and not just the property list ──────────────────
 *
 * A run rebuilt after somebody adjusted a quantity is a different order and
 * must be allowed. If the key ignored quantities, the corrected order would
 * silently replay the wrong one — the worst possible outcome, because it
 * returns success and changes nothing.
 *
 * ── And why the database holds it too ─────────────────────────────────────
 *
 * `laundry_orders.requirement_key` carries a unique constraint. The
 * idempotency store lives in a table with its own retention and could be
 * pruned; the constraint cannot. Belt and braces on the one operation in this
 * module whose duplicate costs real money.
 */

import { COMMITTED_LAUNDRY_STATUSES } from '../contracts/states'
import { fingerprint } from '../service'
import { isoDay } from './dates'
import { calculatedOnly } from './override'
import type {
  ConsolidatedRun,
  LaundryChannel,
  LaundryDispatchMode,
  LaundryMode,
  LaundryOrder,
  LaundryOrderLine,
  LaundrySettings,
} from './types'

/**
 * The stable key for one run.
 *
 * Exported and tested directly, because a key that is *nearly* stable is worse
 * than none: it produces duplicates rarely, under load, in production.
 */
export function orderRequirementKey(run: ConsolidatedRun): string {
  return fingerprint({
    providerId: run.providerId,
    route: run.route,
    day: isoDay(run.requiredBy),
    // Sorted, because a run assembled in a different order is the same run. A
    // Map's insertion order is not a fact about the business.
    lines: run.properties
      .flatMap((property) =>
        property.lines.map((line) => ({
          propertyId: property.propertyId,
          itemId: line.itemId,
          quantity: line.quantity,
        })),
      )
      .sort((a, b) =>
        `${a.propertyId} ${a.itemId}` < `${b.propertyId} ${b.itemId}` ? -1 : 1,
      ),
  })
}

/**
 * The human-facing reference a provider is given.
 *
 * Opaque on purpose. It names the day and carries the run's own fingerprint,
 * so two orders on one day are distinguishable and neither leaks a sequence
 * number — an incrementing order number tells a supplier exactly how much
 * business the organization does, which is not information they are owed.
 *
 * The fingerprint is used WHOLE rather than truncated to a friendlier six
 * characters, and the reason is small but worth stating: a truncation length
 * is an arbitrary constant, `no-hardcoded-numbers.test.ts` scans this
 * directory and admits none, and the honest choice between "add an exception
 * to the guard" and "a slightly longer reference" is the reference. It is
 * copied and pasted far more often than it is read aloud.
 */
export function orderReference(run: ConsolidatedRun): string {
  const day = isoDay(run.requiredBy).split('-').join('')
  return `L${day}-${orderRequirementKey(run)}`.toUpperCase()
}

export interface BuildOrderInput {
  run: ConsolidatedRun
  settings: LaundrySettings
  organizationId: string
  /** Supplied by the caller so the operation stays deterministic. */
  orderId: string
  /** Line ids, one per line, in the order the lines are produced. */
  lineIds: readonly string[]
  channel?: LaundryChannel
  dispatchMode?: LaundryDispatchMode
  internalNotes?: string | null
  providerNotes?: string | null
}

/**
 * Build a draft order from a consolidated run.
 *
 * Always `draft`. Nothing here sends anything, and the dispatch mode is
 * recorded rather than acted on — an order that sent itself because a function
 * was called is the failure `LAUNDRY_DISPATCH_MODES` defaults to
 * `approval_required` to prevent.
 */
export function buildOrder(input: BuildOrderInput): LaundryOrder {
  const { run, settings, organizationId, orderId } = input

  const lines: LaundryOrderLine[] = []
  let index = 0

  for (const property of run.properties) {
    for (const line of property.lines) {
      lines.push({
        id: input.lineIds[index] ?? `${orderId}-${index}`,
        organizationId,
        orderId,
        propertyId: property.propertyId,
        itemId: line.itemId,
        label: line.label,
        unit: line.unit,
        quantity: calculatedOnly(line.quantity),
        requiredBy: line.requiredBy,
        sourceBookingId: line.sourceBookingId,
        explanation: line.explanation,
        notes: null,
      })
      index += 1
    }
  }

  return {
    id: orderId,
    organizationId,
    // NULL when the run spans more than one property. The breakdown is on the
    // lines and is never collapsed — see `consolidation.ts`.
    propertyId:
      run.properties.length === 1
        ? (run.properties[0]?.propertyId ?? null)
        : null,
    providerId: run.providerId,
    status: 'draft',
    mode: modeFor(run, settings),
    dispatchMode: input.dispatchMode ?? settings.dispatchMode,
    channel: input.channel ?? settings.defaultChannel,
    reference: orderReference(run),
    requirementKey: orderRequirementKey(run),
    requiredBy: run.requiredBy,
    pickupAt: null,
    expectedReturnAt: null,
    returnedAt: null,
    sentAt: null,
    sentBody: null,
    internalNotes: input.internalNotes ?? null,
    providerNotes: input.providerNotes ?? null,
    lines,
    version: 1,
  }
}

/**
 * The mode frozen onto the order.
 *
 * The organization's current mode, except that a `hybrid` organization
 * produces an order per route, and each order records the route it actually
 * is. Freezing it means an organization that moves from `external` to
 * `internal` in March does not make February's orders unreadable — the order
 * still knows what kind of thing it was.
 */
function modeFor(run: ConsolidatedRun, settings: LaundrySettings): LaundryMode {
  if (settings.mode !== 'hybrid') return settings.mode
  return run.route === 'external' ? 'external' : 'internal'
}

/**
 * Is this order still freely editable.
 *
 * Mirrors `COMMITTED_LAUNDRY_STATUSES` in the frozen contract rather than
 * restating the list, so the two cannot drift.
 */
export function isCommitted(order: LaundryOrder): boolean {
  return COMMITTED_LAUNDRY_STATUSES.includes(order.status)
}

/**
 * Total pieces in an order, from the final quantities.
 *
 * Uses `final` rather than `calculated`, because the question this answers is
 * "does this reach the provider's minimum", and the provider counts what
 * actually arrives.
 */
export function orderUnits(order: LaundryOrder): number {
  return order.lines.reduce((sum, line) => sum + line.quantity.final, 0)
}
