-- ============================================================================
-- 0012_permission_catalogue.sql — ESTIA · the catalogue catches up with the code
--
-- What this does
--   Reconciles public.permissions, public.roles and public.role_permissions
--   with src/lib/authz/permissions.ts and src/lib/authz/roles.ts, which have
--   moved a long way since 0002 seeded them.
--
--   0002 says the catalogue "must stay identical" to those files. It was not:
--
--       action permissions      98  ->  132
--       field permissions        7  ->   13
--       system roles            16  ->   20   (+ referral_agent, sales_agent,
--                                              senior_agent, agency_manager)
--
-- ── The part that is a security defect and not a tidiness problem ───────────
--
--   `guest.view_contact` was one grant covering a guest's phone and email. It
--   has been split, because the agent network asks a question the single grant
--   could not answer: give an external seller the phone so they can call their
--   own client, and never the email, which is the business's channel for the
--   next stay.
--
--       guest.view_contact  ->  guest.view_phone + guest.view_email
--
--   And a third grant appeared beside them. `guest.view_name` is genuinely new
--   protection: under the old catalogue a name was visible to anyone who could
--   read the row at all, so it was gated by `guest.view` and by nothing else.
--
--   Both facts make this a data migration and not a seed edit. A custom role
--   somebody built in their own organization holds codes this file is changing
--   underneath them, and a role that silently loses a capability during a
--   migration is an integration defect that surfaces as a receptionist who can
--   no longer see a phone number. So, before anything is removed:
--
--     · every custom role holding `guest.view_contact` is granted BOTH
--       `guest.view_phone` and `guest.view_email`;
--     · every custom role holding `guest.view` is granted `guest.view_name`,
--       because that is exactly what it could already see.
--
--   Only then is `guest.view_contact` withdrawn. The order is the migration.
--
-- ── The derived roles ───────────────────────────────────────────────────────
--
--   0002 computes organization_owner and administrator with INSERT … SELECT
--   over the catalogue, so that adding a permission reaches both without
--   anyone editing a list. That is true of the statement, but the statement
--   ran once in 0002 and cannot reach permissions inserted today. The
--   derivation is therefore re-run here, and the assertion at the foot of this
--   file checks the resulting counts against grantsForSystemRole():
--
--       organization_owner  140   (132 actions - 5 platform + 13 fields)
--       administrator       136   (the same, minus the 4 OWNER_ONLY grants)
--
-- ── How the seed below was produced ─────────────────────────────────────────
--
--   Not by hand. The permission rows and every system role's grant set were
--   generated by running permissions.ts and roles.ts and printing what they
--   actually resolve to — including the three ordered ladders roles.ts now
--   composes with (CALENDAR_LEVELS, PRICE_LEVELS, GUEST_DATA_LEVELS), each
--   flattened through grantsForSystemRole() exactly as the engine flattens it.
--   Transcribing 145 codes and 20 grant sets by eye is how a catalogue drifts
--   in the first place.
--
--   Each role block deletes what the role should no longer hold and inserts
--   what it should, so this file is idempotent and also self-correcting: a
--   grant added to a system role by hand is removed the next time it runs.
--   Custom roles are never touched by those blocks — only by the named data
--   migration in section 3.
--
-- Depends on
--   0002_authz.sql (permissions, roles, role_permissions), 0003_plans.sql
--   (plans, and the entitlements CHECK this file widens).
-- ============================================================================

set search_path = public, extensions;


-- ============================================================================
-- 1 · The catalogue
-- ============================================================================
-- Every code in permissions.ts, with its kind, category, owner-only flag and
-- sort order recomputed from the file's own ordering — the same
-- position-times-ten scheme 0002 used, so the database lists permissions in
-- the order a reader of the TypeScript would expect.

insert into public.permissions (code, kind, category, is_owner_only, sort_order)
values
  ('organization.view', 'action'::public.permission_kind, 'organization', false, 10),
  ('organization.settings.edit', 'action'::public.permission_kind, 'organization', false, 20),
  ('organization.billing.manage', 'action'::public.permission_kind, 'organization', true, 30),
  ('organization.transfer_ownership', 'action'::public.permission_kind, 'organization', true, 40),
  ('organization.close', 'action'::public.permission_kind, 'organization', true, 50),
  ('property.view', 'action'::public.permission_kind, 'property', false, 60),
  ('property.create', 'action'::public.permission_kind, 'property', false, 70),
  ('property.update', 'action'::public.permission_kind, 'property', false, 80),
  ('property.delete', 'action'::public.permission_kind, 'property', false, 90),
  ('unit.manage', 'action'::public.permission_kind, 'property', false, 100),
  ('booking.view', 'action'::public.permission_kind, 'booking', false, 110),
  ('booking.create', 'action'::public.permission_kind, 'booking', false, 120),
  ('booking.update', 'action'::public.permission_kind, 'booking', false, 130),
  ('booking.amend_guest_count', 'action'::public.permission_kind, 'booking', false, 140),
  ('booking.amend_extras', 'action'::public.permission_kind, 'booking', false, 150),
  ('booking.amend_dates', 'action'::public.permission_kind, 'booking', false, 160),
  ('booking.amend_price', 'action'::public.permission_kind, 'booking', false, 170),
  ('booking.cancel', 'action'::public.permission_kind, 'booking', false, 180),
  ('booking.delete', 'action'::public.permission_kind, 'booking', false, 190),
  ('booking.change_status', 'action'::public.permission_kind, 'booking', false, 200),
  ('booking.override_price', 'action'::public.permission_kind, 'booking', false, 210),
  ('booking.override_availability', 'action'::public.permission_kind, 'booking', false, 220),
  ('booking.export', 'action'::public.permission_kind, 'booking', false, 230),
  ('booking.assign', 'action'::public.permission_kind, 'booking', false, 240),
  ('booking.note.internal', 'action'::public.permission_kind, 'booking', false, 250),
  ('availability.view', 'action'::public.permission_kind, 'availability', false, 260),
  ('hold.view', 'action'::public.permission_kind, 'availability', false, 270),
  ('hold.create', 'action'::public.permission_kind, 'availability', false, 280),
  ('hold.release', 'action'::public.permission_kind, 'availability', false, 290),
  ('hold.extend', 'action'::public.permission_kind, 'availability', false, 300),
  ('guest.view', 'action'::public.permission_kind, 'guest', false, 310),
  ('guest.create', 'action'::public.permission_kind, 'guest', false, 320),
  ('guest.update', 'action'::public.permission_kind, 'guest', false, 330),
  ('guest.delete', 'action'::public.permission_kind, 'guest', false, 340),
  ('guest.export', 'action'::public.permission_kind, 'guest', false, 350),
  ('lead.view', 'action'::public.permission_kind, 'sales', false, 360),
  ('lead.create', 'action'::public.permission_kind, 'sales', false, 370),
  ('lead.update', 'action'::public.permission_kind, 'sales', false, 380),
  ('lead.assign', 'action'::public.permission_kind, 'sales', false, 390),
  ('quote.view', 'action'::public.permission_kind, 'sales', false, 400),
  ('quote.create', 'action'::public.permission_kind, 'sales', false, 410),
  ('quote.update', 'action'::public.permission_kind, 'sales', false, 420),
  ('quote.send', 'action'::public.permission_kind, 'sales', false, 430),
  ('finance.view', 'action'::public.permission_kind, 'finance', false, 440),
  ('payment.view', 'action'::public.permission_kind, 'finance', false, 450),
  ('payment.create', 'action'::public.permission_kind, 'finance', false, 460),
  ('payment.request_link', 'action'::public.permission_kind, 'finance', false, 470),
  ('payment.capture', 'action'::public.permission_kind, 'finance', false, 480),
  ('payment.refund', 'action'::public.permission_kind, 'finance', false, 490),
  ('payment.void', 'action'::public.permission_kind, 'finance', false, 500),
  ('deposit.hold', 'action'::public.permission_kind, 'finance', false, 510),
  ('deposit.release', 'action'::public.permission_kind, 'finance', false, 520),
  ('expense.view', 'action'::public.permission_kind, 'finance', false, 530),
  ('expense.create', 'action'::public.permission_kind, 'finance', false, 540),
  ('expense.approve', 'action'::public.permission_kind, 'finance', false, 550),
  ('invoice.view', 'action'::public.permission_kind, 'finance', false, 560),
  ('invoice.issue', 'action'::public.permission_kind, 'finance', false, 570),
  ('report.financial.view', 'action'::public.permission_kind, 'finance', false, 580),
  ('report.financial.export', 'action'::public.permission_kind, 'finance', false, 590),
  ('user.view', 'action'::public.permission_kind, 'team', false, 600),
  ('user.invite', 'action'::public.permission_kind, 'team', false, 610),
  ('user.edit', 'action'::public.permission_kind, 'team', false, 620),
  ('user.suspend', 'action'::public.permission_kind, 'team', false, 630),
  ('user.remove', 'action'::public.permission_kind, 'team', false, 640),
  ('role.create', 'action'::public.permission_kind, 'team', false, 650),
  ('role.assign', 'action'::public.permission_kind, 'team', false, 660),
  ('permission.edit', 'action'::public.permission_kind, 'team', true, 670),
  ('team.manage', 'action'::public.permission_kind, 'team', false, 680),
  ('task.view', 'action'::public.permission_kind, 'operations', false, 690),
  ('task.create', 'action'::public.permission_kind, 'operations', false, 700),
  ('task.assign', 'action'::public.permission_kind, 'operations', false, 710),
  ('task.update', 'action'::public.permission_kind, 'operations', false, 720),
  ('task.complete', 'action'::public.permission_kind, 'operations', false, 730),
  ('task.verify', 'action'::public.permission_kind, 'operations', false, 740),
  ('checklist.manage', 'action'::public.permission_kind, 'operations', false, 750),
  ('inventory.view', 'action'::public.permission_kind, 'operations', false, 760),
  ('inventory.edit', 'action'::public.permission_kind, 'operations', false, 770),
  ('incident.view', 'action'::public.permission_kind, 'operations', false, 780),
  ('incident.create', 'action'::public.permission_kind, 'operations', false, 790),
  ('incident.update', 'action'::public.permission_kind, 'operations', false, 800),
  ('incident.resolve', 'action'::public.permission_kind, 'operations', false, 810),
  ('message.view', 'action'::public.permission_kind, 'communication', false, 820),
  ('message.send', 'action'::public.permission_kind, 'communication', false, 830),
  ('message.assign', 'action'::public.permission_kind, 'communication', false, 840),
  ('template.manage', 'action'::public.permission_kind, 'communication', false, 850),
  ('product.view', 'action'::public.permission_kind, 'sales', false, 860),
  ('product.manage', 'action'::public.permission_kind, 'sales', false, 870),
  ('order.view', 'action'::public.permission_kind, 'sales', false, 880),
  ('order.fulfil', 'action'::public.permission_kind, 'sales', false, 890),
  ('review.view', 'action'::public.permission_kind, 'sales', false, 900),
  ('review.manage', 'action'::public.permission_kind, 'sales', false, 910),
  ('site.view', 'action'::public.permission_kind, 'sales', false, 920),
  ('site.edit_content', 'action'::public.permission_kind, 'sales', false, 930),
  ('site.edit_design', 'action'::public.permission_kind, 'sales', false, 940),
  ('site.manage_seo', 'action'::public.permission_kind, 'sales', false, 950),
  ('site.manage_domain', 'action'::public.permission_kind, 'sales', false, 960),
  ('site.publish', 'action'::public.permission_kind, 'sales', false, 970),
  ('site.rollback', 'action'::public.permission_kind, 'sales', false, 980),
  ('site.ai_generate', 'action'::public.permission_kind, 'sales', false, 990),
  ('pricing.manage', 'action'::public.permission_kind, 'sales', false, 1000),
  ('channel.manage', 'action'::public.permission_kind, 'sales', false, 1010),
  ('owner.view', 'action'::public.permission_kind, 'owners', false, 1020),
  ('owner.manage', 'action'::public.permission_kind, 'owners', false, 1030),
  ('owner_statement.view', 'action'::public.permission_kind, 'owners', false, 1040),
  ('owner_statement.issue', 'action'::public.permission_kind, 'owners', false, 1050),
  ('agent.view', 'action'::public.permission_kind, 'agent', false, 1060),
  ('agent.invite', 'action'::public.permission_kind, 'agent', false, 1070),
  ('agent.manage', 'action'::public.permission_kind, 'agent', false, 1080),
  ('agent.scope.manage', 'action'::public.permission_kind, 'agent', false, 1090),
  ('agency.manage', 'action'::public.permission_kind, 'agent', false, 1100),
  ('agent_agreement.view', 'action'::public.permission_kind, 'agent', false, 1110),
  ('agent_agreement.manage', 'action'::public.permission_kind, 'agent', false, 1120),
  ('agent_limits.manage', 'action'::public.permission_kind, 'agent', false, 1130),
  ('agent_booking.approve', 'action'::public.permission_kind, 'agent', false, 1140),
  ('commission.view', 'action'::public.permission_kind, 'agent', false, 1150),
  ('commission.approve', 'action'::public.permission_kind, 'agent', false, 1160),
  ('commission.payout', 'action'::public.permission_kind, 'agent', false, 1170),
  ('agent_statement.view', 'action'::public.permission_kind, 'agent', false, 1180),
  ('agent_statement.issue', 'action'::public.permission_kind, 'agent', false, 1190),
  ('report.agent.view', 'action'::public.permission_kind, 'agent', false, 1200),
  ('agent.audit.view', 'action'::public.permission_kind, 'agent', false, 1210),
  ('audit.view', 'action'::public.permission_kind, 'governance', false, 1220),
  ('approval.request', 'action'::public.permission_kind, 'governance', false, 1230),
  ('approval.decide', 'action'::public.permission_kind, 'governance', false, 1240),
  ('automation.view', 'action'::public.permission_kind, 'governance', false, 1250),
  ('automation.manage', 'action'::public.permission_kind, 'governance', false, 1260),
  ('integration.manage', 'action'::public.permission_kind, 'governance', false, 1270),
  ('platform.organization.view', 'action'::public.permission_kind, 'platform', false, 1280),
  ('platform.organization.manage', 'action'::public.permission_kind, 'platform', false, 1290),
  ('platform.plan.manage', 'action'::public.permission_kind, 'platform', false, 1300),
  ('platform.impersonate', 'action'::public.permission_kind, 'platform', false, 1310),
  ('platform.feature_flag.manage', 'action'::public.permission_kind, 'platform', false, 1320),
  ('guest.view_name', 'field'::public.permission_kind, 'guest', false, 1330),
  ('guest.view_phone', 'field'::public.permission_kind, 'guest', false, 1340),
  ('guest.view_email', 'field'::public.permission_kind, 'guest', false, 1350),
  ('guest.view_document_id', 'field'::public.permission_kind, 'guest', false, 1360),
  ('booking.view_price', 'field'::public.permission_kind, 'booking', false, 1370),
  ('booking.view_payment_status', 'field'::public.permission_kind, 'booking', false, 1380),
  ('booking.view_source', 'field'::public.permission_kind, 'booking', false, 1390),
  ('booking.view_deposit', 'field'::public.permission_kind, 'booking', false, 1400),
  ('booking.view_profitability', 'field'::public.permission_kind, 'booking', false, 1410),
  ('owner.view_commission', 'field'::public.permission_kind, 'owners', false, 1420),
  ('rate.view_public', 'field'::public.permission_kind, 'sales', false, 1430),
  ('rate.view_agent', 'field'::public.permission_kind, 'sales', false, 1440),
  ('rate.view_net', 'field'::public.permission_kind, 'sales', false, 1450)
on conflict (code) do update
  set kind          = excluded.kind,
      category      = excluded.category,
      is_owner_only = excluded.is_owner_only,
      sort_order    = excluded.sort_order;


-- ============================================================================
-- 2 · The four agent-network roles
-- ============================================================================
-- External sellers are members of the organization with a narrow role and a
-- narrow scope, decided by the same engine as everybody else — not a second
-- identity system. Their grant sets are seeded with every other system role
-- in section 5.

insert into public.roles (organization_id, code, name, description, is_system, is_platform, sort_order)
values
  (null, 'referral_agent', 'סוכן הפניה',  'ממליץ בלבד. רואה זמינות, ואינו רואה מחיר ואינו מזמין.',        true, false, 170),
  (null, 'sales_agent',    'סוכן מכירות', 'מוכר שהות: הצעות מחיר, החזקות והזמנות בנכסים שהוקצו לו.',      true, false, 180),
  (null, 'senior_agent',   'סוכן בכיר',   'סוכן מכירות עם מחיר נטו, הנחות רחבות יותר וצפייה בעמלות שלו.', true, false, 190),
  (null, 'agency_manager', 'מנהל סוכנות', 'מנהל צוות סוכנים: היקף, הסכמים, עמלות ודוחות של הסוכנות.',     true, false, 200)
on conflict (code) where organization_id is null do update
  set name        = excluded.name,
      description = excluded.description,
      is_system   = excluded.is_system,
      is_platform = excluded.is_platform,
      sort_order  = excluded.sort_order;


-- ============================================================================
-- 3 · The data migration — nobody loses a capability
-- ============================================================================
-- Custom roles only: organization_id IS NOT NULL. A customer composed these
-- for themselves and this file has no business rewriting them, but it does
-- have a duty not to take something away while renaming it.

-- guest.view_contact was phone AND email. Both replacements, to every custom
-- role that held it.
insert into public.role_permissions (role_id, permission_code)
select rp.role_id, replacement.code
from public.role_permissions rp
join public.roles r on r.id = rp.role_id
cross join (values ('guest.view_phone'), ('guest.view_email')) as replacement(code)
where rp.permission_code = 'guest.view_contact'
  and r.organization_id is not null
on conflict do nothing;

-- A name used to be visible to anyone who could read the guest row at all, so
-- guest.view is what actually conferred it. Withholding guest.view_name here
-- would be the same silent loss in a different column.
insert into public.role_permissions (role_id, permission_code)
select rp.role_id, 'guest.view_name'
from public.role_permissions rp
join public.roles r on r.id = rp.role_id
where rp.permission_code = 'guest.view'
  and r.organization_id is not null
on conflict do nothing;

-- Only now is the old grant withdrawn, from custom and system roles alike.
delete from public.role_permissions where permission_code = 'guest.view_contact';


-- ============================================================================
-- 4 · Retire the split grant
-- ============================================================================
-- The foreign key from role_permissions is ON DELETE RESTRICT, so this
-- statement is itself the proof that section 3 left nothing behind: if any
-- role still held it, this would fail rather than orphan a grant.

delete from public.permissions where code = 'guest.view_contact';


-- ============================================================================
-- 5 · Every system role's grant set, as the engine resolves it
-- ============================================================================
-- One block per role: delete what it should no longer hold, insert what it
-- should. Scoped to organization_id IS NULL throughout, so a customer's own
-- roles are never touched.
--
-- organization_owner and administrator keep the derivation 0002 gave them —
-- a query over the catalogue, not a list — so that a permission added
-- tomorrow reaches both without anyone editing this file. What is new is a
-- DELETE beside each, so a grant that should no longer be on the two most
-- senior roles in the product is corrected rather than accumulated.

-- organization_owner and administrator stay derived, exactly as 0002 wrote
-- them and exactly as grantsForSystemRole() computes them: every non-platform
-- permission, minus OWNER_ONLY for the administrator. Re-running the two
-- statements is what carries today's new permissions onto them; the DELETE
-- half is new, so a grant that should no longer be there goes away too.
delete from public.role_permissions rp
 using public.roles r, public.permissions p
 where r.id = rp.role_id
   and p.code = rp.permission_code
   and r.organization_id is null
   and r.code = 'organization_owner'
   and p.is_platform;

insert into public.role_permissions (role_id, permission_code)
select r.id, p.code
from public.roles r
cross join public.permissions p
where r.code = 'organization_owner'
  and r.organization_id is null
  and not p.is_platform
on conflict do nothing;

delete from public.role_permissions rp
 using public.roles r, public.permissions p
 where r.id = rp.role_id
   and p.code = rp.permission_code
   and r.organization_id is null
   and r.code = 'administrator'
   and (p.is_platform or p.is_owner_only);

insert into public.role_permissions (role_id, permission_code)
select r.id, p.code
from public.roles r
cross join public.permissions p
where r.code = 'administrator'
  and r.organization_id is null
  and not p.is_platform
  and not p.is_owner_only
on conflict do nothing;

-- general_manager — 88 grants
with target as (
  select id from public.roles where code = 'general_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'hold.view', 'hold.create', 'hold.release', 'hold.extend', 'quote.view',
    'quote.create', 'quote.update', 'quote.send', 'lead.view',
    'lead.create', 'lead.update', 'rate.view_public',
    'payment.request_link', 'booking.create', 'booking.update',
    'guest.update', 'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.change_status',
    'booking.assign', 'booking.note.internal', 'guest.create',
    'guest.view_name', 'guest.view_phone', 'guest.view_email',
    'booking.view_price', 'booking.view_payment_status', 'message.view',
    'message.send', 'task.view', 'task.create', 'task.assign',
    'task.update', 'task.complete', 'task.verify', 'checklist.manage',
    'incident.view', 'incident.create', 'incident.update',
    'incident.resolve', 'inventory.view', 'inventory.edit',
    'booking.override_price', 'booking.override_availability',
    'booking.export', 'booking.view_source', 'guest.export',
    'property.create', 'property.update', 'unit.manage', 'pricing.manage',
    'product.view', 'product.manage', 'order.view', 'order.fulfil',
    'review.view', 'review.manage', 'user.view', 'user.invite',
    'team.manage', 'message.assign', 'template.manage', 'automation.view',
    'expense.view', 'expense.create', 'approval.request', 'agent.view',
    'agent.invite', 'agent.manage', 'agent.scope.manage', 'agency.manage',
    'agent_agreement.view', 'agent_agreement.manage', 'agent_limits.manage',
    'agent_booking.approve', 'agent.audit.view', 'commission.view',
    'agent_statement.view', 'report.agent.view', 'lead.assign',
    'rate.view_agent', 'rate.view_net'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- property_manager — 65 grants
with target as (
  select id from public.roles where code = 'property_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'hold.view', 'hold.create', 'hold.release', 'hold.extend', 'quote.view',
    'quote.create', 'quote.update', 'quote.send', 'lead.view',
    'lead.create', 'lead.update', 'rate.view_public',
    'payment.request_link', 'booking.create', 'booking.update',
    'guest.update', 'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.change_status',
    'booking.assign', 'booking.note.internal', 'guest.create',
    'guest.view_name', 'guest.view_phone', 'guest.view_email',
    'booking.view_price', 'booking.view_payment_status', 'message.view',
    'message.send', 'task.view', 'task.create', 'task.assign',
    'task.update', 'task.complete', 'task.verify', 'checklist.manage',
    'incident.view', 'incident.create', 'incident.update',
    'incident.resolve', 'inventory.view', 'inventory.edit',
    'booking.export', 'booking.view_source', 'unit.manage', 'agent.view',
    'agent_booking.approve', 'lead.assign', 'rate.view_agent',
    'property.update', 'product.view', 'order.view', 'order.fulfil',
    'review.view', 'user.view', 'message.assign', 'expense.view',
    'expense.create', 'approval.request'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- reservation_manager — 49 grants
with target as (
  select id from public.roles where code = 'reservation_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'hold.view', 'hold.create', 'hold.release', 'hold.extend', 'quote.view',
    'quote.create', 'quote.update', 'quote.send', 'lead.view',
    'lead.create', 'lead.update', 'rate.view_public',
    'payment.request_link', 'booking.create', 'booking.update',
    'guest.update', 'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.change_status',
    'booking.assign', 'booking.note.internal', 'guest.create',
    'guest.view_name', 'guest.view_phone', 'guest.view_email',
    'booking.view_price', 'booking.view_payment_status', 'message.view',
    'message.send', 'booking.override_price',
    'booking.override_availability', 'booking.export',
    'booking.view_source', 'booking.view_deposit', 'payment.view',
    'payment.create', 'invoice.view', 'template.manage', 'approval.request',
    'agent.view', 'agent_booking.approve', 'lead.assign', 'rate.view_agent'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- reception — 41 grants
with target as (
  select id from public.roles where code = 'reception' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'hold.view', 'hold.create', 'hold.release', 'hold.extend', 'quote.view',
    'quote.create', 'quote.update', 'quote.send', 'lead.view',
    'lead.create', 'lead.update', 'rate.view_public',
    'payment.request_link', 'booking.update', 'guest.update',
    'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.change_status',
    'booking.note.internal', 'guest.create', 'guest.view_name',
    'guest.view_phone', 'guest.view_email', 'booking.view_price',
    'booking.view_payment_status', 'booking.view_deposit', 'message.view',
    'message.send', 'task.view', 'task.create', 'incident.create',
    'payment.view', 'payment.create', 'order.view', 'order.fulfil'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- revenue_manager — 16 grants
with target as (
  select id from public.roles where code = 'revenue_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'booking.view_price', 'booking.view_source', 'pricing.manage',
    'booking.override_price', 'channel.manage', 'report.financial.view',
    'unit.manage', 'rate.view_public', 'rate.view_agent', 'rate.view_net',
    'agent_limits.manage', 'report.agent.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- finance_manager — 43 grants
with target as (
  select id from public.roles where code = 'finance_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'booking.view', 'availability.view', 'guest.view', 'property.view',
    'finance.view', 'payment.view', 'payment.create',
    'payment.request_link', 'payment.capture', 'payment.refund',
    'payment.void', 'deposit.hold', 'deposit.release', 'expense.view',
    'expense.create', 'expense.approve', 'invoice.view', 'invoice.issue',
    'report.financial.view', 'report.financial.export',
    'booking.view_price', 'booking.view_payment_status',
    'booking.view_deposit', 'booking.view_profitability', 'guest.view_name',
    'guest.view_phone', 'guest.view_email', 'owner.view',
    'owner_statement.view', 'owner_statement.issue',
    'owner.view_commission', 'approval.decide', 'booking.export',
    'commission.view', 'commission.approve', 'commission.payout',
    'agent_agreement.view', 'agent_statement.view', 'agent_statement.issue',
    'report.agent.view', 'rate.view_public', 'rate.view_agent',
    'rate.view_net'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- accountant — 12 grants
with target as (
  select id from public.roles where code = 'accountant' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'finance.view', 'payment.view', 'expense.view', 'invoice.view',
    'report.financial.view', 'report.financial.export', 'booking.view',
    'booking.view_price', 'property.view', 'owner_statement.view',
    'commission.view', 'agent_statement.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- operations_manager — 22 grants
with target as (
  select id from public.roles where code = 'operations_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'task.view', 'task.create', 'task.assign', 'task.update',
    'task.complete', 'task.verify', 'checklist.manage', 'incident.view',
    'incident.create', 'incident.update', 'incident.resolve',
    'inventory.view', 'inventory.edit', 'booking.view', 'availability.view',
    'guest.view', 'property.view', 'user.view', 'team.manage',
    'expense.view', 'expense.create', 'approval.request'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- housekeeping_supervisor — 15 grants
with target as (
  select id from public.roles where code = 'housekeeping_supervisor' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'task.view', 'task.create', 'task.assign', 'task.update',
    'task.complete', 'task.verify', 'checklist.manage', 'incident.view',
    'incident.create', 'incident.update', 'inventory.view',
    'inventory.edit', 'user.view', 'property.view', 'booking.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- cleaner — 4 grants
with target as (
  select id from public.roles where code = 'cleaner' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'task.view', 'task.update', 'task.complete', 'incident.create'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- maintenance — 7 grants
with target as (
  select id from public.roles where code = 'maintenance' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'task.view', 'task.update', 'task.complete', 'incident.view',
    'incident.create', 'incident.update', 'inventory.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- property_owner — 4 grants
with target as (
  select id from public.roles where code = 'property_owner' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'property.view', 'booking.view', 'owner_statement.view',
    'report.financial.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- external_vendor — 3 grants
with target as (
  select id from public.roles where code = 'external_vendor' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'task.view', 'task.update', 'task.complete'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- marketing_editor — 9 grants
with target as (
  select id from public.roles where code = 'marketing_editor' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'site.view', 'site.edit_content', 'site.edit_design', 'site.manage_seo',
    'site.ai_generate', 'review.view', 'review.manage', 'product.view',
    'property.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- referral_agent — 4 grants
with target as (
  select id from public.roles where code = 'referral_agent' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'lead.view', 'lead.create', 'commission.view', 'agent_statement.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- sales_agent — 19 grants
with target as (
  select id from public.roles where code = 'sales_agent' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'lead.view', 'lead.create', 'commission.view', 'agent_statement.view',
    'availability.view', 'rate.view_public', 'quote.view', 'quote.create',
    'quote.update', 'quote.send', 'hold.view', 'hold.create',
    'hold.release', 'hold.extend', 'booking.view', 'booking.create',
    'guest.create', 'rate.view_agent', 'lead.update'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- senior_agent — 27 grants
with target as (
  select id from public.roles where code = 'senior_agent' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'lead.view', 'lead.create', 'commission.view', 'agent_statement.view',
    'availability.view', 'rate.view_public', 'quote.view', 'quote.create',
    'quote.update', 'quote.send', 'hold.view', 'hold.create',
    'hold.release', 'hold.extend', 'booking.view', 'booking.create',
    'guest.create', 'rate.view_agent', 'lead.update', 'guest.update',
    'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.cancel',
    'booking.view_payment_status', 'payment.request_link'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;

-- agency_manager — 35 grants
with target as (
  select id from public.roles where code = 'agency_manager' and organization_id is null
), wanted(code) as (
  select unnest(array[
    'lead.view', 'lead.create', 'commission.view', 'agent_statement.view',
    'availability.view', 'rate.view_public', 'quote.view', 'quote.create',
    'quote.update', 'quote.send', 'hold.view', 'hold.create',
    'hold.release', 'hold.extend', 'booking.view', 'booking.create',
    'guest.create', 'rate.view_agent', 'rate.view_net', 'guest.view_name',
    'guest.view_phone', 'lead.update', 'lead.assign', 'guest.update',
    'booking.amend_guest_count', 'booking.amend_extras',
    'booking.amend_dates', 'booking.amend_price', 'booking.cancel',
    'booking.view_payment_status', 'payment.request_link', 'agent.view',
    'agent.invite', 'agent_agreement.view', 'report.agent.view'
  ]::text[])
), removed as (
  delete from public.role_permissions rp using target t
   where rp.role_id = t.id and rp.permission_code not in (select code from wanted)
  returning 1
)
insert into public.role_permissions (role_id, permission_code)
select t.id, w.code from target t cross join wanted w
on conflict do nothing;


-- ============================================================================
-- 6 · Platform roles
-- ============================================================================
-- Re-run from 0002 unchanged, so that a platform permission added to the
-- catalogue today reaches ESTIA's own staff. These are the two roles
-- grantsForSystemRole() does not resolve: roles.ts models them as a separate
-- list because they are never assignable inside a customer organization, and
-- the rule "platform_super_admin holds every platform.*" is expressed as a
-- query in both places.

insert into public.role_permissions (role_id, permission_code)
select r.id, p.code
from public.roles r
cross join public.permissions p
where r.code = 'platform_super_admin'
  and r.organization_id is null
  and p.is_platform
on conflict do nothing;

insert into public.role_permissions (role_id, permission_code)
select r.id, p.code
from public.roles r
cross join public.permissions p
where r.code = 'platform_support'
  and r.organization_id is null
  and p.code = 'platform.organization.view'
on conflict do nothing;


-- ============================================================================
-- 7 · The agent network as a package feature
-- ============================================================================
-- `agent_network` joins ENTITLEMENTS in src/lib/plans/entitlements.ts, so the
-- CHECK that keeps the column honest has to learn it before any plan can
-- carry it. Dropped and recreated rather than altered, because a CHECK cannot
-- be modified in place.

alter table public.plans drop constraint if exists plans_entitlements_known;
alter table public.plans add constraint plans_entitlements_known check (
  entitlements <@ array[
    'core', 'payments', 'invoicing', 'website', 'ai_content', 'custom_domain',
    'team', 'operations', 'channels', 'dynamic_pricing', 'owner_portal',
    'agent_network', 'approvals', 'automation', 'custom_roles', 'multi_brand',
    'api_access'
  ]::text[]
);

-- Direct, Pro and Management include it. Basic deliberately does not: it is
-- sold to Basic as a per-customer add-on through
-- organization_subscriptions.entitlement_grants, which is why that column
-- exists and why selling it needs no schema change.
--
-- Written as an append rather than an assignment, so a plan whose entitlements
-- an operator has since edited keeps the edit.
update public.plans
   set entitlements = entitlements || array['agent_network']::text[]
 where code in ('direct', 'pro', 'management')
   and not (entitlements @> array['agent_network']::text[]);


-- ============================================================================
-- 8 · Drift fails loudly
-- ============================================================================
-- 0002 carried the same guard with the numbers of its day (98 and 7). Updated
-- here, and widened: the two derived roles are checked as well, because their
-- counts are the ones that silently go wrong when a permission is added to the
-- catalogue and the derivation is not re-run — which is exactly the bug this
-- migration exists to repair.

do $$
declare
  action_count integer;
  field_count  integer;
  owner_count  integer;
  admin_count  integer;
begin
  select count(*) into action_count from public.permissions where kind = 'action';
  select count(*) into field_count  from public.permissions where kind = 'field';
  if action_count <> 132 or field_count <> 13 then
    raise exception
      'permission catalogue drift: expected 132 action and 13 field permissions, found % and %',
      action_count, field_count;
  end if;

  select count(*) into owner_count
    from public.role_permissions rp
    join public.roles r on r.id = rp.role_id
   where r.code = 'organization_owner' and r.organization_id is null;

  select count(*) into admin_count
    from public.role_permissions rp
    join public.roles r on r.id = rp.role_id
   where r.code = 'administrator' and r.organization_id is null;

  -- grantsForSystemRole() in src/lib/authz/roles.ts resolves these to 140 and
  -- 136. If the database disagrees, one of the two has moved without the other.
  if owner_count <> 140 or admin_count <> 136 then
    raise exception
      'derived role drift: expected organization_owner 140 and administrator 136, found % and %',
      owner_count, admin_count;
  end if;

  if exists (select 1 from public.permissions where code = 'guest.view_contact') then
    raise exception 'guest.view_contact still exists; the split in section 3 did not complete';
  end if;
end $$;


-- ============================================================================
-- 9 · Commissions get their real gate
-- ============================================================================
-- 0011 gated `commissions` on `finance.view` and said why: the narrower codes
-- existed in permissions.ts but not in the database, and a policy naming a
-- code no role can hold denies everybody. Section 1 has just seeded them, so
-- the provisional gate can go.
--
-- `finance.view` was too wide in both directions. It let an accountant with a
-- read-only remit write a commission row, and it made the agent network's own
-- three-way split — see who is owed, approve it, pay it — invisible to the
-- database. commission.approve and commission.payout are deliberately not held
-- by whoever wrote the commission rule.

drop policy if exists commissions_select on public.commissions;
create policy commissions_select on public.commissions
  for select to authenticated
  using (
    organization_id in (select public.my_organizations())
    and public.property_in_scope(property_id, organization_id)
    and public.has_permission(organization_id, 'commission.view')
  );

drop policy if exists commissions_insert on public.commissions;
create policy commissions_insert on public.commissions
  for insert to authenticated
  with check (
    organization_id in (select public.my_organizations())
    and public.property_in_scope(property_id, organization_id)
    and public.has_permission(organization_id, 'commission.approve')
  );

-- Either grant, because the two acts that move a commission up its ladder are
-- held by different people on purpose: approving what is owed, and paying it.
drop policy if exists commissions_update on public.commissions;
create policy commissions_update on public.commissions
  for update to authenticated
  using (
    organization_id in (select public.my_organizations())
    and public.property_in_scope(property_id, organization_id)
    and (
      public.has_permission(organization_id, 'commission.approve')
      or public.has_permission(organization_id, 'commission.payout')
    )
  )
  with check (
    organization_id in (select public.my_organizations())
    and public.property_in_scope(property_id, organization_id)
    and (
      public.has_permission(organization_id, 'commission.approve')
      or public.has_permission(organization_id, 'commission.payout')
    )
  );
