import type { Metadata } from 'next'
import Link from 'next/link'

import type { SearchParams } from '@/app/(auth)/_lib/search-params'
import { firstParam } from '@/app/(auth)/_lib/search-params'
import { ActionError } from '@/components/booking/action-error'
import {
  Panel,
  PanelNote,
  Row,
  RowList,
  ScreenFrame,
} from '@/components/shell-screens/screen'
import { Badge } from '@/components/ui/badge'
import { toSafeResponse } from '@/lib/errors'
import {
  KIND_LABEL,
  MIN_QUERY_LENGTH,
  parseQuery,
  planSearch,
} from '@/lib/search'
import { createClient } from '@/lib/supabase/server'

import { shellContext } from '../_lib/context'
import { searchKind, type SearchHit } from './_lib/queries'

export const metadata: Metadata = { title: 'חיפוש · ESTIA' }

/**
 * EXECUTION CONTEXT — SERVER COMPONENT. One box, seven kinds of thing.
 *
 * ══ WHY THIS SCREEN EXISTS ══════════════════════════════════════════════════
 *
 * Spec 6.0 §96, and it was absent entirely: there was no way to type a guest's
 * phone number and find them. Every screen had its own filter and none of them
 * crossed. The first thing anybody does with a booking system all day is look
 * something up, and the product could not do it.
 *
 * ══ THREE THINGS THIS DOES THAT A NAIVE SEARCH DOES NOT ═════════════════════
 *
 * **It reads the string before it queries.** `parseQuery` decides what the
 * input IS — a phone, an email, a booking reference, or text — and the kinds
 * that cannot match are never queried. An email costs one round trip rather
 * than seven.
 *
 * **A phone goes through the database's own normaliser.** `guests.phone_e164`
 * is generated by `normalize_phone_il`, so `050-123-4567` and `+972501234567`
 * are one number to the schema and must be one number to the search. `/guests`
 * puts the raw string into an `ilike` and therefore finds nobody; that is a
 * recorded defect and this screen does not inherit it.
 *
 * **Every kind is gated separately, before the query.** One box reaching seven
 * tables is the most efficient way ever invented to hand somebody rows they
 * may not read. `planSearch` drops each closed kind so its query is never
 * ISSUED — fetch-then-filter is how a count leaks what a list withholds.
 *
 * ══ AND IT SAYS WHAT IT DID NOT SEARCH ══════════════════════════════════════
 *
 * Deliberately, against the tempting alternative of quietly searching less. A
 * receptionist who searches a guest's phone, finds nothing, and concludes the
 * guest is not in the system has been misled by silence — the system did not
 * look. Naming the closed kind leaks the shape of the product, which the menu
 * already shows, and never a row or a count.
 */
export default async function SearchPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>
}) {
  const [context, params] = await Promise.all([shellContext(), searchParams])

  if (!context || context.status !== 'ready') return null

  const { actor } = context
  const raw = firstParam(params.q) ?? ''
  const parsed = parseQuery(raw)

  const lead =
    'שם, טלפון, אימייל, מספר הזמנה או שם נכס. החיפוש מזהה מה הקלדת ומחפש רק ' +
    'במה שיכול להתאים — ורק במה שההרשאות שלך פותחות.'

  if (parsed === null) {
    return (
      <ScreenFrame title="חיפוש" lead={lead} width="prose">
        <SearchBox value={raw} />
        <Panel title="הקלד כדי לחפש">
          <PanelNote>
            נדרשים לפחות {MIN_QUERY_LENGTH} תווים. תו אחד מתאים כמעט לכל שורה
            במערכת, וזו אינה תוצאת חיפוש.
          </PanelNote>
        </Panel>
      </ScreenFrame>
    )
  }

  const plan = planSearch(actor, parsed.kinds)

  let hits: readonly SearchHit[] = []
  let failure: ReturnType<typeof toSafeResponse> | null = null

  try {
    const db = await createClient()
    const results = await Promise.all(
      plan.searchable.map((kind) =>
        searchKind(kind, {
          db,
          organizationId: actor.organizationId,
          parsed,
        }),
      ),
    )
    // Flattened in the order the parser ranked the kinds, so a phone search
    // shows the guest before the bookings that merely contain the digits.
    hits = results.flat()
  } catch (cause) {
    failure = toSafeResponse(cause, crypto.randomUUID())
  }

  return (
    <ScreenFrame title="חיפוש" lead={lead} width="prose">
      <SearchBox value={raw} />

      {failure ? (
        <ActionError error={failure.error} />
      ) : (
        <Panel
          title={`תוצאות עבור ״${parsed.text}״`}
          count={hits.length}
          description={SHAPE_NOTE[parsed.shape]}
        >
          {plan.searchable.length === 0 ? (
            <PanelNote>
              אין לך הרשאה לאף אחד מסוגי הרשומות שהמחרוזת הזאת יכולה להתאים להם,
              ולכן לא בוצע חיפוש כלל.
            </PanelNote>
          ) : hits.length === 0 ? (
            <PanelNote>
              לא נמצאה התאמה ב
              {plan.searchable.map((k) => KIND_LABEL[k]).join(' · ')}.
            </PanelNote>
          ) : (
            <RowList>
              {hits.map((hit) => (
                <Row key={`${hit.kind}:${hit.id}`}>
                  {/*
                    The whole row is the target, not a link inside a label.
                    This is a jump-to screen: a person is already reaching for
                    the thing they searched, and a small text link is the wrong
                    size for a thumb — §103 asks for mobile-friendly actions.
                  */}
                  <Link
                    href={hit.href}
                    className="-m-1 flex min-h-11 items-center justify-between gap-3 rounded-lg p-1 transition-colors hover:bg-muted focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
                  >
                    <span className="font-medium text-foreground">
                      {hit.title}
                    </span>
                    <span className="flex shrink-0 items-center gap-2">
                      {hit.subtitle !== null && (
                        <span className="text-xs text-muted-foreground">
                          {hit.subtitle}
                        </span>
                      )}
                      <Badge>{KIND_LABEL[hit.kind]}</Badge>
                    </span>
                  </Link>
                </Row>
              ))}
            </RowList>
          )}

          {/*
            What was searched, and what was not. The second half is the one
            that matters: a person who finds nothing needs to know whether the
            system looked.
          */}
          <PanelNote>
            נחפש ב:{' '}
            {plan.searchable.map((k) => KIND_LABEL[k]).join(' · ') || '—'}
          </PanelNote>
          {plan.closed.length > 0 && (
            <PanelNote>
              לא נחפש ב{plan.closed.map((k) => KIND_LABEL[k]).join(' · ')} — אין
              לך הרשאה או שהחבילה אינה כוללת אותם. זו אינה קביעה שאין שם התאמה.
            </PanelNote>
          )}
        </Panel>
      )}
    </ScreenFrame>
  )
}

/** What the parser decided, said out loud so a surprising result is explicable. */
const SHAPE_NOTE: Readonly<Record<string, string>> = {
  phone:
    'זוהה כמספר טלפון. ההתאמה היא על המספר המנורמל, כך ש-050-1234567 ו-+972501234567 הם אותו אדם.',
  email: 'זוהה כאימייל, ולכן החיפוש הוא באורחים בלבד.',
  reference:
    'זוהה כמספר הזמנה, ולכן ההזמנות ראשונות — אבל גם נכסים ויחידות נבדקו.',
  text: 'טקסט חופשי, ולכן נבדק כל סוג רשומה שההרשאות שלך פותחות.',
}

/**
 * A plain form, and deliberately not a client component.
 *
 * A GET form puts the query in the URL, which makes a search shareable, back-
 * navigable and bookmarkable for free — and costs no JavaScript. An instant
 * type-ahead would need a client component, a debounce and a request per
 * keystroke against seven tables, which is a great deal of machinery to make a
 * screen feel faster than pressing enter.
 */
function SearchBox({ value }: { value: string }) {
  return (
    <form action="/search" method="get" className="flex gap-2">
      <input
        type="search"
        name="q"
        defaultValue={value}
        autoFocus
        placeholder="שם · טלפון · אימייל · מספר הזמנה · נכס"
        aria-label="חיפוש"
        className="min-h-11 w-full rounded-xl border border-border-strong bg-surface px-4 text-sm text-foreground placeholder:text-muted-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
      />
      <button
        type="submit"
        className="min-h-11 shrink-0 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground shadow-soft transition-opacity hover:opacity-90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
      >
        חפש
      </button>
    </form>
  )
}
