'use server'

/**
 * EXECUTION CONTEXT — SERVER ACTION. Recording an enquiry and moving it along.
 *
 * ── Not one function here writes a row ────────────────────────────────────
 *
 * Each hands the request to an operation in `src/lib/leads`, which is the only
 * path with authorization, validation, the business rule, the transaction, the
 * audit event and idempotency wired in that order. What is left here is the
 * shape of the request and the wiring of the services, exactly as
 * `guests/_lib/actions.ts` does it.
 *
 * ── `assertCan` is called here as well, and that is not belt-and-braces ───
 *
 * `leads_insert` requires `lead.create` at the database and `leads_update`
 * requires `lead.update`, so these checks are not the enforcement. They are the
 * independent one: a Server Action is reachable by a crafted POST whatever the
 * screen rendered, and it must refuse on its own terms before it has read or
 * written anything.
 *
 * ── The telephone number is normalised by the database, never here ────────
 *
 * `resolveGuest` calls `public.normalize_phone_il` over RPC rather than
 * reimplementing it. `guests.phone_e164` and `leads.phone_e164` are both
 * generated by that function, so asking it is the only way to compare like
 * with like — and a second normaliser in TypeScript would be a second answer
 * to "is this the same person", which is the decision this whole module exists
 * to get right. `src/lib/leads/matching.ts` says the same thing at length.
 */

import { revalidatePath } from 'next/cache'

import { assertCan } from '@/lib/authz/can'
import { toSafeResponse, type SafeErrorBody } from '@/lib/errors'
import {
  attachmentFor,
  defineLeadOperations,
  type LeadDraft,
  type LeadSnapshot,
  type LeadStatus,
  type MatchableGuest,
} from '@/lib/leads'
import type { LeadLostReason, LeadSource } from '@/lib/leads'
import {
  SupabaseAuditWriter,
  SupabaseIdempotencyStore,
  asNumber,
  asString,
  asStringOrNull,
  toRow,
  toRows,
  type Db,
} from '@/lib/persistence'
import type { BookingStatusName } from '@/lib/revenue/types'
import { createClient } from '@/lib/supabase/server'

import { domainEventBus } from '../../_lib/events'
import { shellContext } from '../../_lib/context'
import { auditActorFor, transactionRunner } from '../../_lib/wiring'

export type ActionResult<TData> =
  { ok: true; data: TData } | { ok: false; error: SafeErrorBody }

function refusal(
  code: string,
  message: string,
): { ok: false; error: SafeErrorBody } {
  return {
    ok: false,
    error: {
      code,
      message,
      dataMessage: 'הנתונים לא נשמרו. שום דבר במערכת לא השתנה.',
      retryMessage: 'ניסיון חוזר לא יעזור עד שהבעיה תיפתר.',
      dataOutcome: 'not_saved',
      retryable: false,
      correlationId: crypto.randomUUID(),
    },
  }
}

async function requireReady() {
  const context = await shellContext()
  if (!context) {
    return refusal(
      'unauthenticated',
      'החיבור למערכת פג. התחבר מחדש כדי להמשיך.',
    )
  }
  if (context.status !== 'ready') {
    return refusal(
      'membership_not_active',
      'אין לך מרחב עבודה פעיל, ולכן לא ניתן לעבוד עם פניות.',
    )
  }
  return { ok: true as const, context }
}

/* ------------------------------------------------------- what it reads -- */

function buildOperations(db: Db) {
  return defineLeadOperations({
    db,

    async loadLead(organizationId, leadId): Promise<LeadSnapshot | null> {
      const { data, error } = await db
        .from('leads')
        .select(
          'id, property_id, status, version, raw_name, assigned_to_user_id, ' +
            'created_by, first_response_at',
        )
        .eq('organization_id', organizationId)
        .eq('id', leadId)
        .is('deleted_at', null)
        .maybeSingle()

      if (error) throw error
      if (!data) return null

      const row = toRow(data)
      return {
        id: asString(row, 'id'),
        propertyId: asStringOrNull(row, 'property_id'),
        status: asString(row, 'status') as LeadStatus,
        version: asNumber(row, 'version'),
        // Used in the audit sentence. "פנייה ללא שם" and not a made-up name:
        // an enquiry from a number with no name attached is a real thing, and
        // a timeline that invents one is a timeline that cannot be trusted.
        displayName: asStringOrNull(row, 'raw_name') ?? 'פנייה ללא שם',
        assignedToUserId: asStringOrNull(row, 'assigned_to_user_id'),
        createdByUserId: asStringOrNull(row, 'created_by'),
        firstResponseAt: asStringOrNull(row, 'first_response_at'),
      }
    },

    async resolveGuest(organizationId, lead) {
      const phoneE164 = await normalisePhoneInDatabase(db, lead.rawPhone)
      const emailNormalized = normaliseEmailLikeTheColumn(lead.rawEmail)
      if (phoneE164 === null && emailNormalized === null) return null

      // Candidates by either key, then `attachmentFor` decides. Two separate
      // reads rather than one `.or()`: PostgREST's `or` over two columns is
      // easy to get subtly wrong, and being wrong here attaches an enquiry to
      // a stranger.
      const candidates = new Map<string, MatchableGuest>()

      for (const [column, value] of [
        ['phone_e164', phoneE164],
        ['email', emailNormalized],
      ] as const) {
        if (value === null) continue
        const { data, error } = await db
          .from('guests')
          .select('id, full_name, phone_e164, email')
          .eq('organization_id', organizationId)
          .is('deleted_at', null)
          .eq(column, value)
          .limit(10)

        if (error) throw error
        for (const row of toRows(data)) {
          candidates.set(asString(row, 'id'), {
            id: asString(row, 'id'),
            fullName: asStringOrNull(row, 'full_name') ?? '',
            phoneE164: asStringOrNull(row, 'phone_e164'),
            email: asStringOrNull(row, 'email'),
          })
        }
      }

      const attachment = attachmentFor({ phoneE164, emailNormalized }, [
        ...candidates.values(),
      ])
      // Only an exact telephone match attaches. `suggest` is written to the
      // screen for a person, never applied here (ח40-08).
      return attachment.kind === 'attach' ? attachment.guestId : null
    },

    async loadBookingStatus(organizationId, bookingId) {
      const { data, error } = await db
        .from('bookings')
        .select('status')
        .eq('organization_id', organizationId)
        .eq('id', bookingId)
        .is('deleted_at', null)
        .maybeSingle()

      if (error) throw error
      if (!data) return null
      return asString(toRow(data), 'status') as BookingStatusName
    },

    async loadMergeTargets(organizationId, survivorId, mergedId) {
      const { data, error } = await db
        .from('guests')
        .select('id, full_name, version')
        .eq('organization_id', organizationId)
        .in('id', [survivorId, mergedId])

      if (error) throw error
      const rows = toRows(data)
      const survivor = rows.find((row) => asString(row, 'id') === survivorId)
      const merged = rows.find((row) => asString(row, 'id') === mergedId)
      if (!survivor || !merged) return null

      return {
        survivorName: asStringOrNull(survivor, 'full_name') ?? '',
        survivorVersion: asNumber(survivor, 'version'),
        mergedVersion: asNumber(merged, 'version'),
      }
    },
  })
}

/**
 * The database's own normalisation, asked for rather than copied.
 *
 * `normalize_phone_il` is `IMMUTABLE` and granted to `authenticated`, and it
 * is what generated every `phone_e164` in the table this is about to be
 * compared against.
 */
async function normalisePhoneInDatabase(
  db: Db,
  raw: string | null,
): Promise<string | null> {
  if (raw === null || raw.trim().length === 0) return null
  const { data, error } = await db.rpc('normalize_phone_il', { raw })
  if (error) throw error
  return typeof data === 'string' && data.length > 0 ? data : null
}

/** `leads.email_normalized` is `nullif(lower(btrim(raw_email)), '')`. */
function normaliseEmailLikeTheColumn(raw: string | null): string | null {
  if (raw === null) return null
  const trimmed = raw.trim().toLowerCase()
  return trimmed.length > 0 ? trimmed : null
}

/* -------------------------------------------------------- the actions -- */

export type RecordEnquiryInput = LeadDraft & { idempotencyKey: string }

export async function recordEnquiryAction(
  input: RecordEnquiryInput,
): Promise<ActionResult<{ id: string; attachedToGuest: boolean }>> {
  const gate = await requireReady()
  if (!gate.ok) return gate

  const { context } = gate
  const correlationId = crypto.randomUUID()

  try {
    assertCan(context.actor, 'lead.create', {
      organizationId: context.actor.organizationId,
      propertyId: input.propertyId ?? undefined,
      family: 'booking',
    })

    const supabase = await createClient()
    const { transactions } = transactionRunner(supabase)
    const operations = buildOperations(supabase)

    const outcome = await operations.record.run({
      request: {
        input: {
          source: input.source,
          sourceDetail: orNull(input.sourceDetail),
          propertyId: input.propertyId,
          rawName: orNull(input.rawName),
          rawPhone: orNull(input.rawPhone),
          rawEmail: orNull(input.rawEmail),
          requestedCheckIn: orNull(input.requestedCheckIn),
          requestedCheckOut: orNull(input.requestedCheckOut),
          partyAdults: input.partyAdults,
          partyChildren: input.partyChildren,
          partyInfants: input.partyInfants,
          budgetAgorot: input.budgetAgorot,
          message: orNull(input.message),
        } satisfies LeadDraft,
        idempotencyKey: input.idempotencyKey,
      },
      context: {
        actor: context.actor,
        auditActor: auditActorFor(context.user),
        correlationId,
      },
      services: {
        audit: new SupabaseAuditWriter(supabase),
        events: domainEventBus(supabase),
        idempotency: new SupabaseIdempotencyStore(supabase),
        transactions,
        onEventError(error) {
          console.error('[leads] domain event delivery failed', error)
        },
      },
    })

    revalidatePath('/leads')
    return {
      ok: true,
      data: {
        id: outcome.data.id,
        attachedToGuest: outcome.data.guestId !== null,
      },
    }
  } catch (cause) {
    return { ok: false, error: toSafeResponse(cause, correlationId).error }
  }
}

export type ChangeStatusInput = {
  leadId: string
  status: LeadStatus
  lostReason: LeadLostReason | null
  lostNote: string | null
  bookingId: string | null
  note: string | null
  expectedVersion: number
}

export async function changeEnquiryStatusAction(
  input: ChangeStatusInput,
): Promise<ActionResult<{ id: string }>> {
  const gate = await requireReady()
  if (!gate.ok) return gate

  const { context } = gate
  const correlationId = crypto.randomUUID()

  try {
    assertCan(context.actor, 'lead.update', {
      organizationId: context.actor.organizationId,
      family: 'booking',
    })

    const supabase = await createClient()
    const { transactions } = transactionRunner(supabase)
    const operations = buildOperations(supabase)

    const outcome = await operations.changeStatus.run({
      request: {
        input: {
          leadId: input.leadId,
          status: input.status,
          lostReason: input.lostReason,
          lostNote: orNull(input.lostNote),
          bookingId: input.bookingId,
          note: orNull(input.note),
        },
        resourceId: input.leadId,
        // Optimistic locking, because the board is a screen two people work at
        // once: a card dragged from a stale column would otherwise overwrite a
        // colleague's decision without either of them seeing it.
        expectedVersion: input.expectedVersion,
      },
      context: {
        actor: context.actor,
        auditActor: auditActorFor(context.user),
        correlationId,
        reason: orNull(input.note),
      },
      services: {
        audit: new SupabaseAuditWriter(supabase),
        events: domainEventBus(supabase),
        transactions,
        onEventError(error) {
          console.error('[leads] domain event delivery failed', error)
        },
      },
    })

    revalidatePath('/leads')
    return { ok: true, data: { id: outcome.data.id } }
  } catch (cause) {
    return { ok: false, error: toSafeResponse(cause, correlationId).error }
  }
}

function orNull(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null
  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : null
}

export type { LeadSource }
